SELECT DISTINCT PAB.ACTION_CODE "ActionCode"
	, PARM.ROLE_COMMON_NAME "Role"
	, PASTT.USER_STATUS "AssignmentStatus"
FROM PER_ACTIONS_B PAB
	LEFT JOIN PER_ACTION_ROLE_MAPPING PARM
	ON PARM.ACT_USG_ID = PAB.ACTION_ID
		LEFT JOIN PER_ASSIGNMENT_STATUS_TYPES_TL PASTT
		ON PAB.DFLT_ASG_STATUS_TYPE_ID = PASTT.ASSIGNMENT_STATUS_TYPE_ID
		AND PASTT.LANGUAGE = 'D'
WHERE 1 = 1
	AND PAB.START_DATE NOT LIKE PAB.END_DATE
	AND (PARM.ROLE_COMMON_NAME IS NOT NULL OR PASTT.USER_STATUS IS NOT NULL)
ORDER BY PAB.ACTION_CODE
