SELECT DISTINCT PCAFT.COLLECTIVE_AGREEMENT_NAME "CollectiveAgreement"
	, PCAF.IDENTIFICATION_CODE "Code"
FROM PER_COL_AGREEMENTS_F PCAF
	, PER_COL_AGREEMENTS_F_TL PCAFT
WHERE 1 = 1
	AND PCAF.COLLECTIVE_AGREEMENT_ID = PCAFT.COLLECTIVE_AGREEMENT_ID
	AND PCAFT.LANGUAGE = PCAFT.SOURCE_LANG
ORDER BY PCAF.IDENTIFICATION_CODE
