SELECT DISTINCT PAPF.PERSON_NUMBER "PersonNumber"
	, TO_CHAR(PAPF.EFFECTIVE_START_DATE, 'YYYY/MM/DD') "EffectiveStartDate"
	, PPNF.TITLE "Title"
	, PPNF.FIRST_NAME "FirstName"
	, PPNF.LAST_NAME "LastName"
	, PPLF.MARITAL_STATUS "MaritalStatus"
	, PPLF.SEX "Sex"
	, HOUFT_LE.NAME "LegalEmployerName"
	, HOUFT_BU.NAME "BusinessUnitShortCode"
	, PAAM.ASSIGNMENT_NUMBER "AssignmentNumber"
	, HAPFT.NAME "Position"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
FROM PER_PERSON_NAMES_F PPNF
	, PER_ALL_PEOPLE_F PAPF
	, PER_PEOPLE_LEGISLATIVE_F PPLF
	, PER_PERIODS_OF_SERVICE PPOS
	, HRC_INTEGRATION_KEY_MAP HIKM
	, PER_ALL_ASSIGNMENTS_M PAAM
	, HR_ORGANIZATION_UNITS_F_TL HOUFT_LE
	, HR_ALL_POSITIONS_F_TL HAPFT
	, HR_ORGANIZATION_UNITS_F_TL HOUFT_BU
WHERE 1 = 1
	AND PPNF.PERSON_ID = PAPF.PERSON_ID
	AND PAPF.PERSON_ID = HIKM.SURROGATE_ID
	AND PPOS.PERSON_ID = PAAM.PERSON_ID
	AND PPLF.PERSON_ID = PAPF.PERSON_ID
	AND PPOS.PERSON_ID = PAPF.PERSON_ID
	AND HOUFT_BU.ORGANIZATION_ID = PAAM.BUSINESS_UNIT_ID
	AND HOUFT_LE.ORGANIZATION_ID = PPOS.LEGAL_ENTITY_ID
	AND HOUFT_LE.LANGUAGE = HOUFT_LE.SOURCE_LANG
	AND PPNF.NAME_TYPE = 'GLOBAL'
	AND PAAM.ASSIGNMENT_TYPE NOT LIKE '%T'
	AND HAPFT.LANGUAGE = HAPFT.SOURCE_LANG
	AND HOUFT_BU.LANGUAGE = HOUFT_BU.SOURCE_LANG
	AND HAPFT.POSITION_ID = PAAM.POSITION_ID
	AND SYSDATE BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PPLF.EFFECTIVE_START_DATE AND PPLF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN HAPFT.EFFECTIVE_START_DATE AND HAPFT.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN HOUFT_LE.EFFECTIVE_START_DATE AND HOUFT_LE.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN HOUFT_BU.EFFECTIVE_START_DATE AND HOUFT_BU.EFFECTIVE_END_DATE
	AND HIKM.OBJECT_NAME = 'Person'
	AND PAPF.PERSON_NUMBER LIKE nvl(:PersonNumber, PERSON_NUMBER)
	AND PPNF.FIRST_NAME LIKE nvl(:FirstName, FIRST_NAME)
	AND PPNF.LAST_NAME LIKE nvl(:LastName, LAST_NAME)
ORDER BY PERSON_NUMBER
