SELECT DISTINCT PGLFT.NAME
FROM PER_GRADE_LADDERS_F_TL PGLFT
	, PER_GRADES_IN_LADDERS_F PGILF
	, PER_GRADES_F_TL PGFT
WHERE 1 = 1
	AND PGLFT.GRADE_LADDER_ID = PGILF.GRADE_LADDER_ID
	AND PGILF.GRADE_ID = PGFT.GRADE_ID
	AND PGFT.NAME LIKE nvl(:Grade, PGFT.NAME)
	AND PGLFT.LANGUAGE = PGLFT.SOURCE_LANG
	AND PGFT.LANGUAGE = PGFT.SOURCE_LANG
	AND SYSDATE BETWEEN PGLFT.EFFECTIVE_START_DATE AND PGLFT.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PGILF.EFFECTIVE_START_DATE AND PGILF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PGFT.EFFECTIVE_START_DATE AND PGFT.EFFECTIVE_END_DATE
ORDER BY PGLFT.NAME
