-- simplified

SELECT DISTINCT FLVT.LOOKUP_TYPE "LookupType"
	, COUNT(DISTINCT FLVB.LOOKUP_CODE) "NumberOfLookupCodes"
FROM FND_LOOKUP_VALUES_B FLVB
	, FND_LOOKUP_VALUES_TL FLVT
WHERE 1 = 1
    AND FLVT.LANGUAGE = FLVT.SOURCE_LANG
	AND FLVB.LOOKUP_TYPE = FLVT.LOOKUP_TYPE
	AND LOOKUP_TYPE LIKE NVL(:LookupType, FLVT.LOOKUP_TYPE)
GROUP BY FLVT.LOOKUP_TYPE
ORDER BY FLVT.LOOKUP_TYPE
