SELECT DISTINCT PAPF.PERSON_NUMBER "PersonNumber"
	, PPNF.DISPLAY_NAME "DisplayName"
	, PGLFT.NAME "GradeLadder"
	, PRF.RATE_FREQUENCY "Frequency"
	, CS.SALARY_AMOUNT "Salary"
	, CS.CREATED_BY "CreatedBy"
	, TO_CHAR(CS.CREATION_DATE, 'YYYY/MM/DD') "CreationDate"
	, CS.LAST_UPDATED_BY "LastUpdatedBy"
	, TO_CHAR(CS.LAST_UPDATE_DATE, 'YYYY/MM/DD') "LastUpdateDate"
FROM PER_ALL_PEOPLE_F PAPF
	, PER_PERSON_NAMES_F PPNF
	, PER_RATES_F PRF
	, PER_GRADE_LADDERS_F_TL PGLFT
	, CMP_SALARY CS
	, PER_ALL_ASSIGNMENTS_M PAAM
WHERE 1 = 1
	AND PAPF.PERSON_ID = PPNF.PERSON_ID
	AND PPNF.PERSON_ID = PAPF.PERSON_ID
	AND PRF.GRADE_LADDER_ID = PGLFT.GRADE_LADDER_ID
	AND CS.PERSON_ID (+) = PAPF.PERSON_ID
	AND PAAM.PERSON_ID = PAPF.PERSON_ID
	AND PAAM.GRADE_LADDER_PGM_ID = PGLFT.GRADE_LADDER_ID
	AND PPNF.NAME_TYPE = 'GLOBAL'
	AND PGLFT.LANGUAGE = PGLFT.SOURCE_LANG
	AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
	AND PAAM.PRIMARY_FLAG = 'Y'
	AND PAAM.ASSIGNMENT_TYPE NOT LIKE '%T'
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PRF.EFFECTIVE_START_DATE AND PRF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PGLFT.EFFECTIVE_START_DATE AND PGLFT.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
	AND PAPF.PERSON_NUMBER LIKE NVL(:PersonNumber, PAPF.PERSON_NUMBER)
	AND PPNF.DISPLAY_NAME LIKE NVL(:DisplayName, PPNF.DISPLAY_NAME)
ORDER BY PPNF.DISPLAY_NAME, PAPF.PERSON_NUMBER
