SELECT DISTINCT PPNF.LAST_NAME "LastName"
	, PAPF.PERSON_NUMBER "PersonNumber"
	, PPNF.DISPLAY_NAME "DisplayName"
	, PU.USERNAME "Username"
	, PPNF.FIRST_NAME || '.' || PPNF.LAST_NAME "FirstName.LastName"
	, PU.CREATED_BY "CreatedBy"
	, TO_CHAR(PU.CREATION_DATE, 'YYYY/MM/DD') "CreationDate"
	, PU.LAST_UPDATED_BY "LastUpdatedBy"
	, TO_CHAR(PU.LAST_UPDATE_DATE, 'YYYY/MM/DD') "LastUpdateDate"
	, 'MERGE' "METADATA"
	, 'User' "User"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
FROM PER_ALL_PEOPLE_F PAPF
	LEFT JOIN PER_USERS PU
	ON PAPF.PERSON_ID = PU.PERSON_ID
	, PER_PERSON_NAMES_F PPNF
	, HRC_INTEGRATION_KEY_MAP HIKM
WHERE 1 = 1
	AND HIKM.SURROGATE_ID = PU.USER_ID
	AND PAPF.PERSON_ID = PPNF.PERSON_ID
	AND PPNF.NAME_TYPE = 'GLOBAL'
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
	AND HIKM.OBJECT_NAME = 'User'
	AND PAPF.PERSON_NUMBER BETWEEN '00001226' AND '03003240'
	AND PPNF.DISPLAY_NAME LIKE NVL(:Name, PPNF.DISPLAY_NAME)
	AND PU.USERNAME LIKE NVL(:Username, PU.USERNAME)
	AND PAPF.PERSON_NUMBER = NVL(:PersonNumber, PAPF.PERSON_NUMBER)
ORDER BY PPNF.LAST_NAME
